[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Daniel Naschberger <daniel@naschi.at>"]
edition = "2021"
description = "My solutions to Advent of Code 2021"
repository = "https://github.com/naschidaniel/advent-of-code/"
license = "GPL-3.0"

[dependencies]
